import type { Metadata } from 'next'
import Link from 'next/link'
import { LegalPageLayout, type LegalSection } from '@/components/LegalPageLayout'
import { businessEmail, businessAddress } from '@/lib/businessInfo'

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description:
    'How Armour Infosec collects, uses, stores, and protects information for training, consulting, and website services.',
  alternates: { canonical: '/privacy-policy/' },
}

const SECTIONS: LegalSection[] = [
  {
    id: 'information-we-collect',
    heading: 'Information We Collect',
    body: (
      <>
        <p>We collect information you provide directly and information generated by your interaction with our services.</p>
        <ul className="list-disc pl-6 space-y-1.5">
          <li><strong>Account &amp; enrolment data:</strong> name, email, phone, billing information, course preferences.</li>
          <li><strong>Engagement data:</strong> scoping documents, technical contacts, and authorisation letters required to deliver assessments.</li>
          <li><strong>Usage data:</strong> IP address, browser type, device identifiers, pages visited, referring URL.</li>
          <li><strong>Lab activity data:</strong> command history, exercise progress, and module completion status.</li>
        </ul>
      </>
    ),
  },
  {
    id: 'how-we-use',
    heading: 'How We Use Information',
    body: (
      <>
        <p>We use the information we collect to:</p>
        <ul className="list-disc pl-6 space-y-1.5">
          <li>Deliver, operate, and improve our training, consulting, and assessment services.</li>
          <li>Provision lab access, verify enrolment, and issue certifications or attendance records.</li>
          <li>Process payments and maintain accounting records as required by law.</li>
          <li>Communicate scheduling, support, or service-related information.</li>
          <li>Detect, prevent, and respond to fraud, abuse, or security incidents.</li>
        </ul>
      </>
    ),
  },
  {
    id: 'cookies',
    heading: 'Cookies & Analytics',
    body: (
      <>
        <p>
          We use a small number of essential cookies to keep the website functional (theme preference, session continuity). We may also use privacy-respecting analytics to understand aggregate usage patterns and improve content; analytics data does not include personally identifying details.
        </p>
        <p>
          You can disable non-essential cookies via your browser settings. Disabling essential cookies may affect site functionality.
        </p>
      </>
    ),
  },
  {
    id: 'training-data',
    heading: 'Training Registration Data',
    body: (
      <>
        <p>
          For learners, we maintain records of enrolment, attendance, assessment scores, lab activity, and certification status. This information is used to verify completion, issue credentials, and support continuing education or employer-reimbursement requests.
        </p>
        <p>
          Trainer comments and progress notes are confidential to the learner and authorised Armour Infosec staff.
        </p>
      </>
    ),
  },
  {
    id: 'security',
    heading: 'Security Practices',
    body: (
      <>
        <p>
          We apply ISO 9001:2015 aligned operational controls and industry-standard technical safeguards including TLS 1.2+ in transit, encrypted storage at rest, role-based access control, principle of least privilege for staff access, and regular security review of our infrastructure.
        </p>
        <p>
          No system can guarantee absolute security. If you suspect a vulnerability or breach, please contact us immediately at{' '}
          <a href={`mailto:${businessEmail}`} className="text-accent hover:underline">
            {businessEmail}
          </a>.
        </p>
      </>
    ),
  },
  {
    id: 'third-party-sharing',
    heading: 'Third-Party Sharing',
    body: (
      <>
        <p>We share personal data only with the following categories of recipients, and only as needed:</p>
        <ul className="list-disc pl-6 space-y-1.5">
          <li>Payment processors and accounting providers, to bill and reconcile fees.</li>
          <li>Email and communication providers, to deliver service-related messages.</li>
          <li>Cloud and hosting providers under contractual data-processing agreements.</li>
          <li>Legal, regulatory, or law-enforcement bodies where required by applicable law.</li>
        </ul>
        <p>
          We do <strong>not</strong> sell, rent, or trade personal data to data brokers or advertisers.
        </p>
      </>
    ),
  },
  {
    id: 'retention',
    heading: 'Data Retention',
    body: (
      <>
        <p>
          We retain personal data only for as long as necessary to deliver the services and to comply with legal, tax, and regulatory obligations.
        </p>
        <ul className="list-disc pl-6 space-y-1.5">
          <li>Training and certification records: up to seven (7) years to support credential verification.</li>
          <li>Billing and accounting records: as required by applicable tax law (typically 7 years).</li>
          <li>Marketing data: until you unsubscribe or request deletion.</li>
          <li>Engagement deliverables: per the relevant Statement of Work, typically 24 months after delivery.</li>
        </ul>
      </>
    ),
  },
  {
    id: 'user-rights',
    heading: 'User Rights',
    body: (
      <>
        <p>Subject to applicable law, you have the right to:</p>
        <ul className="list-disc pl-6 space-y-1.5">
          <li>Access the personal data we hold about you.</li>
          <li>Request correction of inaccurate or incomplete data.</li>
          <li>Request deletion where there is no overriding legal obligation to retain.</li>
          <li>Withdraw consent for any processing based on consent.</li>
          <li>Receive a portable copy of data you have provided to us.</li>
          <li>Lodge a complaint with the relevant data-protection authority.</li>
        </ul>
        <p>
          To exercise these rights, email{' '}
          <a href={`mailto:${businessEmail}`} className="text-accent hover:underline">
            {businessEmail}
          </a>{' '}with sufficient information for us to verify your identity. We respond to verified requests within 30 days where feasible.
        </p>
      </>
    ),
  },
  {
    id: 'compliance',
    heading: 'GDPR / Privacy Compliance',
    body: (
      <>
        <p>
          Where the EU General Data Protection Regulation, UK GDPR, or India&rsquo;s Digital Personal Data Protection Act applies, our lawful bases for processing include contract performance, legitimate interest in delivering and securing our services, and consent where explicitly obtained.
        </p>
        <p>
          For cross-border transfers, we rely on appropriate safeguards including standard contractual clauses and contractual data-processing agreements with our sub-processors.
        </p>
      </>
    ),
  },
  {
    id: 'contact',
    heading: 'Contact Information',
    body: (
      <>
        <p>For privacy questions, data-subject requests, or to report a concern, please contact us:</p>
        <ul className="space-y-1.5">
          <li>
            Email:{' '}
            <a href={`mailto:${businessEmail}`} className="text-accent hover:underline">
              {businessEmail}
            </a>
          </li>
          <li>Address: {businessAddress.full}</li>
          <li>
            Or use the <Link href="/contact/" className="text-accent hover:underline">contact form</Link>.
          </li>
        </ul>
      </>
    ),
  },
]

export default function PrivacyPolicyPage() {
  return (
    <LegalPageLayout
      tag="// Privacy"
      title="Privacy Policy"
      description="How Armour Infosec collects, uses, stores, and protects your information."
      lastUpdated="17 May 2026"
      sections={SECTIONS}
    />
  )
}
